kind: pipeline
name: default

clone:
  depth: 10

steps:
- name: docker-latest
  image: plugins/docker
  settings:
    username: drone
    password:
      from_secret: DOCKER_PASSWORD
    repo: 192.168.41.34/dev/demo
    registry: 192.168.41.34
    auto_tag: true
    insecure: true
    debug: true
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT}
  when:
    branch:
      - master
    event:
      - push

- name: docker-release
  image: plugins/docker
  settings:
    username: drone
    password:
      from_secret: DOCKER_PASSWORD
    repo: 192.168.41.34/dev/demo
    registry: 192.168.41.34
    tags:
      - ${DRONE_TAG}
      - latest
    insecure: true
    debug: true
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT}
      - GIT_TAG=${DRONE_TAG}
  when:
    event:
      - tag

- name: deploy
  image: appleboy/drone-ssh 
  settings:
    host: 
       - 192.168.41.35
    username: root
    password:
      from_secret: HOST_PASSWORD
    port: 22
    command_timeout: 2m 
    script:
       - echo "deploy ssh!"
       - docker pull 192.168.41.34/dev/demo:latest
       - docker rm -f demo-test || true
       - docker run --name=demo-test -d -p 8002:8080 192.168.41.34/dev/demo
